twitter: "https://twitter.com/typinks_blog"
github: ""
instagram: "https://www.instagram.com/typinks/"
linkedin: "https://www.linkedin.com/company/typinks/"
dribbble: ""
youtube: ""
facebook: "https://www.facebook.com//Typinks-100225822086682/"
medium: ""
patreon: ""
paypal: ""
unsplash: ""
